name: CI/CD with Github Actions and AWS

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: yarn install
    - name: Lint the app
      run: npx eslint . --ext .js,.jsx,.ts,.tsx
    - name: Fix linting errors/warnings
      run: ./node_modules/.bin/eslint src --fix
    - name: Build the app
      run: yarn build
    - name: Deploy the app to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --delete --exclude '.DS_Store' --exclude 'node_modules/**' --exclude 'src/**'
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-central-1'
        SOURCE_DIR: './dist'